sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  # download Snowflake drivers
  - >-
   docker
   run
   -e AWS_ACCESS_KEY_ID=$AWS_ODBC_KEY
   -e AWS_SECRET_ACCESS_KEY=$AWS_ODBC_SECRET
   -v `pwd`:/code
   quay.io/keboola/aws-cli
   s3 cp s3://keboola-configs/drivers/snowflake/snowflake_linux_x8664_odbc-2.16.6.tgz /code/snowflake_linux_x8664_odbc.tgz
  - docker-compose build app
  - docker-compose run --rm app composer install
  - docker-compose run --rm app composer ci

script:
  - docker-compose run -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN app

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

#notifications:
#  slack: $SLACK_INTEGRATION_DOMAIN:$SLACK_INTEGRATION_KEY
