version: '2'
services:
  app:
    build: .
    image: keboola/wr-db-snowflake
    volumes:
      - .:/code
    working_dir: /code
    command: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      - KBC_RUNID
      - STORAGE_API_TOKEN
      - SNOWFLAKE_DB_HOST
      - SNOWFLAKE_DB_PORT
      - SNOWFLAKE_DB_USER
      - SNOWFLAKE_DB_PASSWORD
      - SNOWFLAKE_DB_DATABASE
      - SNOWFLAKE_DB_SCHEMA
      - SNOWFLAKE_DB_WAREHOUSE

