version: '2'
services:
  app:
    build: .
    image: keboola/wr-db-snowflake
    volumes:
      - .:/code
    working_dir: /code
    command: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      - KBC_RUNID
      - STORAGE_API_TOKEN
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - DB_SCHEMA
      - DB_WAREHOUSE

  php:
    image: keboola/docker-php56-all-db
    volumes:
        - .:/code
    working_dir: /code
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
