version: '2'
services:
  app: &default
    build: .
    image: keboola/wr-db-snowflake
    environment:
      - KBC_RUNID
      - KBC_URL
      - STORAGE_API_TOKEN_S3
      - STORAGE_API_TOKEN_ABS
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - DB_SCHEMA
      - DB_WAREHOUSE

  dev:
    <<: *default
    volumes:
      - .:/code
