name: GitHub Actions
on: [ push ]
concurrency: ci # shared KBC projects are used
env:
  # Name of the image
  APP_IMAGE: keboola/wr-db-snowflake # must be same in docker-compose.yml

  # Developer portal login
  KBC_DEVELOPERPORTAL_VENDOR: "keboola"
  KBC_DEVELOPERPORTAL_APP_S3: "keboola.wr-db-snowflake"
  KBC_DEVELOPERPORTAL_APP_ABS: "keboola.wr-snowflake-blob-storage"
  KBC_DEVELOPERPORTAL_USERNAME: "keboola+db_writer_snowflake_gha"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}

  # DockerHub login
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Test DB
  DB_HOST: kebooladev.snowflakecomputing.com
  DB_PORT: 443
  DB_USER: snowflake_writer
  DB_PASSWORD: ${{ secrets.SNOWFLAKE_DB_PASSWORD }}
  DB_DATABASE: snowflake_writer
  DB_WAREHOUSE: snowflake_writer

  # Testing staging storage projects
  KBC_RUNID: "1234"
  KBC_URL_S3: "https://connection.keboola.com"
  PROJECT_URL_S3: "https://connection.keboola.com/admin/projects/2703"
  STORAGE_API_TOKEN_S3: ${{ secrets.KBC_STORAGE_TOKEN_S3 }}
  DB_SCHEMA_S3: snowflake_writer_s3
  KBC_URL_ABS: "https://connection.north-europe.azure.keboola.com"
  PROJECT_URL_ABS: "https://connection.north-europe.azure.keboola.com/admin/projects/3820"
  STORAGE_API_TOKEN_ABS: ${{ secrets.KBC_STORAGE_TOKEN_ABS }}
  DB_SCHEMA_ABS: snowflake_writer_abs
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_image_tag: ${{ steps.tag.outputs.app_image_tag }}
      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Print Docker version
        run: docker -v
      -
        name: Docker login
        if: env.DOCKERHUB_TOKEN
        run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
      -
        name: Build image
        run: docker build -t $APP_IMAGE .
      -
        name: Set image tag
        id: tag
        run: |
          TAG="${GITHUB_REF##*/}"
          IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
          echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
          echo "is_semantic_tag=$IS_SEMANTIC_TAG" >> $GITHUB_OUTPUT
          echo "app_image_tag=$TAG" >> $GITHUB_OUTPUT
      -
        name: Push image to ECR (S3)
        uses: keboola/action-push-to-ecr@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP_S3 }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ steps.tag.outputs.app_image_tag }}
          push_latest: ${{ steps.tag.outputs.is_semantic_tag }}
          source_image: ${{ env.APP_IMAGE}}

      -
        name: Push image to ECR (ABS)
        uses: keboola/action-push-to-ecr@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP_ABS }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ steps.tag.outputs.app_image_tag }}
          push_latest: ${{ steps.tag.outputs.is_semantic_tag }}
          source_image: ${{ env.APP_IMAGE}}

  tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        staging_storage:
          - S3
          - ABS
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Pull image from ECR
        uses: keboola/action-pull-from-ecr@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP_S3 }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.build.outputs.app_image_tag }}
          target_image: ${{ env.APP_IMAGE}}
          tag_as_latest: true
      -
        name: Run tests
        run: |
          docker compose run --rm \
          -e DB_SCHEMA=${{ env[format('DB_SCHEMA_{0}', matrix.staging_storage)] }} \
          -e KBC_URL=${{ env[format('KBC_URL_{0}', matrix.staging_storage)] }} \
          -e STORAGE_API_TOKEN=${{ env[format('STORAGE_API_TOKEN_{0}', matrix.staging_storage)] }} \
          app composer ci

  deploy:
    needs:
      - build
      - tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && needs.build.outputs.is_semantic_tag == 'true'
    steps:
      -
        name: Set tag in the Deloper Portal (S3)
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP_S3 }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.build.outputs.app_image_tag }}
      -
        name: Set tag in the Deloper Portal (ABS)
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP_ABS }}
          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ needs.build.outputs.app_image_tag }}

